In [1]:
import sys
import os
from os.path import dirname, realpath, join
base_dir = dirname(dirname(dirname(os.getcwd())))
import itertools
from mutex import MutEx
import pandas as pd
from os.path import join
base_dir

'/Users/haithamelmarakeby/PycharmProjects/pnet2'

In [2]:
sys.path.insert(0, base_dir)
from config_path import PROSTATE_DATA_PATH, PLOTS_PATH
from data.data_access import Data

In [3]:
# interesting_genes = [('AR', 'cnv_amp'),
# ('TP53', 'mut_important'),
# ('MDM4', 'cnv_amp'),
# ('CDK4', 'cnv_amp'),
# ('CDK6', 'cnv_amp'),
# ('CDKN2A', 'cnv_del'),
# ('RB1', 'mut_important')]
# pairs = list(itertools.combinations(interesting_genes, 2))

In [4]:
selected_genes = ['AR', 'TP53', 'MDM4', 'CDK4', 'CDK6', 'CDKN2A', 'RB1']
data_params =  {'data_type': ['mut_important', 'cnv_del', 'cnv_amp'],
                 'drop_AR': False,
                 'cnv_levels': 5,
                 'mut_binary': True,
                 'balanced_data': False,
                 'combine_type': 'union',  # intersection
                 'use_coding_genes_only': False,
                 'selected_genes': selected_genes}

data_access_params= {'id': 'id', 'type': 'prostate_paper', 'params': data_params}

In [5]:
data_adapter = Data(**data_access_params)
x, y, info, columns = data_adapter.get_data()
x_df = pd.DataFrame(x, columns= columns, index= info)
x_df.head()

TP53                          CDK4                  \
               mut_important cnv_del cnv_amp mut_important cnv_del cnv_amp   
00-029N9_LN              0.0     0.5     0.0           0.0     0.0     0.0   
01-087MM_BONE            0.0     0.0     0.0           0.0     0.0     0.5   
01-095N1_LN              0.0     0.5     0.0           0.0     0.0     0.0   
01-120A1_LIVER           0.0     0.5     0.0           0.0     0.0     0.0   
02-083E1_LN              0.0     0.0     0.0           0.0     0.0     0.0   

                          AR                           RB1  ...          \
               mut_important cnv_del cnv_amp mut_important  ... cnv_amp   
00-029N9_LN              0.0     0.0     0.0           0.0  ...     0.0   
01-087MM_BONE            1.0     0.0     0.0           0.0  ...     0.0   
01-095N1_LN              0.0     0.0     0.0           0.0  ...     0.0   
01-120A1_LIVER           0.0     0.0     0.0           0.0  ...     0.0   
02-083E1_LN              0.0     0.0     0.5           0.0  ...     0.0   

                      CDKN2A                          CDK6                  \
               mut_important cnv_del cnv_amp mut_important cnv_del cnv_amp   
00-029N9_LN              0.0     0.0     0.0           0.0     0.0     0.0   
01-087MM_BONE            0.0     0.0     0.0           0.0     0.0     0.0   
01-095N1_LN              0.0     0.0     0.0           0.0     0.0     0.0   
01-120A1_LIVER           0.0     0.0     0.0           0.0     0.0     0.0   
02-083E1_LN              0.0     0.0     0.0           0.0     0.0     0.0   

                        MDM4                  
               mut_important cnv_del cnv_amp  
00-029N9_LN              0.0     0.0     0.0  
01-087MM_BONE            0.0     0.0     0.0  
01-095N1_LN              0.0     0.0     0.0  
01-120A1_LIVER           0.0     0.0     0.0  
02-083E1_LN              0.0     0.0     0.5  

[5 rows x 21 columns]

In [6]:
#include single copy amp and delete
# x_df_5= x_df.copy()
# x_df_5[x_df_5>0] = 1
# x_df_5.shape

# high amp and deep del
# x_df_3= x_df.copy()
# x_df_3[x_df_3<1] = 0

In [7]:
x_df_5 = x_df.T.reset_index().groupby('level_0').sum()
x_df_5[x_df_5>0] = 1
x_df_5.shape

(7, 1011)

In [8]:
x_df_3= x_df.copy()
x_df_3[x_df_3<1] = 0 #remove single copy

x_df_3 = x_df_3.T.reset_index().groupby('level_0').sum() # all events (OR)
x_df_3[x_df_3>0] = 1 # binarize 
x_df_3.shape

(7, 1011)

In [9]:
y_ind = y>0
x_df_mets_3 = x_df_3.T[y_ind].T
x_df_mets_5 = x_df_5.T[y_ind].T


In [10]:
selected_genes = ['AR', 'TP53', 'MDM4', 'CDK4', 'CDK6', 'CDKN2A', 'RB1']
pairs = list(itertools.combinations(selected_genes, 2))

In [11]:
x_df_3.head()

00-029N9_LN  01-087MM_BONE  01-095N1_LN  01-120A1_LIVER  02-083E1_LN  \
level_0                                                                         
AR               0.0            1.0          0.0             0.0          0.0   
CDK4             0.0            0.0          0.0             0.0          0.0   
CDK6             0.0            0.0          0.0             0.0          0.0   
CDKN2A           0.0            0.0          0.0             0.0          0.0   
MDM4             0.0            0.0          0.0             0.0          0.0   

         03-082H1_LIVER  03-130L_RETROPERITONEAL  03-139E3_RETROPERITONEAL  \
level_0                                                                      
AR                  1.0                      0.0                       0.0   
CDK4                0.0                      0.0                       0.0   
CDK6                0.0                      0.0                       0.0   
CDKN2A              0.0                      0.0                       0.0   
MDM4                0.0                      0.0                       0.0   

         03-163S4_LIVER  03-192B_LUNG  ...  TP_2032  TP_2034  TP_2054  \
level_0                                ...                              
AR                  0.0           0.0  ...      1.0      1.0      0.0   
CDK4                0.0           0.0  ...      0.0      0.0      0.0   
CDK6                0.0           0.0  ...      0.0      0.0      0.0   
CDKN2A              0.0           0.0  ...      0.0      0.0      0.0   
MDM4                0.0           0.0  ...      0.0      0.0      0.0   

         TP_2060  TP_2061  TP_2064  TP_2069  TP_2077  TP_2078  TP_2079  
level_0                                                                 
AR           1.0      1.0      1.0      0.0      0.0      0.0      1.0  
CDK4         0.0      0.0      0.0      0.0      0.0      0.0      0.0  
CDK6         0.0      0.0      0.0      0.0      0.0      0.0      0.0  
CDKN2A       0.0      0.0      0.0      0.0      0.0      0.0      0.0  
MDM4         0.0      0.0      1.0      0.0      0.0      0.0      0.0  

[5 rows x 1011 columns]

In [12]:
x_df_3.T.AR.value_counts()

0.0    844
1.0    167
Name: AR, dtype: int64

## Mutex

In [13]:
import random
random.seed(18)

def run_mutex(x_df, pairs, permutations =2000, saving_file='mutex' ):
    results=[]
#     df = x_df.copy()
#     df = df.T
    df=x_df.astype(int)
    m = MutEx(background=df, permutations=permutations)
    for g1, g2 in pairs:
        print (g1)
        print (g2)
        r = m.calculate([g1, g2], parallel=True)
        print (r.mutex_pvalue, r.co_occurence_pvalue)
        results.append(r)
    
    results_dict_list=[]
    for r in results:
        g1, g2 = r.items
        results_dict={}
        results_dict['g1'] = g1
        results_dict['g2'] = g2
        results_dict['mutex_pvalue'] = r.mutex_pvalue
        results_dict['co_occurence_pvalue'] = r.co_occurence_pvalue
        results_dict['zscore'] = r.zscore
        results_dict['signal'] = r.signal
        results_dict['coverage'] = r.coverage
        results_dict['signal_coverage_ratio'] = r.signal_coverage_ratio
        results_dict_list.append(results_dict)
    results_df = pd.DataFrame(results_dict_list)
    cols= ['g1', 'g2', 'mutex_pvalue', 'co_occurence_pvalue', 'zscore', 'signal', 'coverage', 'signal_coverage_ratio']
    results_df = results_df.reindex(cols, axis=1)
    results_df.to_csv('{}.csv'.format(saving_file))
    return results_df

In [14]:
x_df_5.head()

00-029N9_LN  01-087MM_BONE  01-095N1_LN  01-120A1_LIVER  02-083E1_LN  \
level_0                                                                         
AR               0.0            1.0          0.0             0.0          1.0   
CDK4             0.0            1.0          0.0             0.0          0.0   
CDK6             0.0            0.0          0.0             0.0          0.0   
CDKN2A           0.0            0.0          0.0             0.0          0.0   
MDM4             0.0            0.0          0.0             0.0          1.0   

         03-082H1_LIVER  03-130L_RETROPERITONEAL  03-139E3_RETROPERITONEAL  \
level_0                                                                      
AR                  1.0                      0.0                       0.0   
CDK4                0.0                      0.0                       0.0   
CDK6                0.0                      0.0                       0.0   
CDKN2A              0.0                      0.0                       0.0   
MDM4                0.0                      1.0                       0.0   

         03-163S4_LIVER  03-192B_LUNG  ...  TP_2032  TP_2034  TP_2054  \
level_0                                ...                              
AR                  0.0           0.0  ...      1.0      1.0      0.0   
CDK4                0.0           0.0  ...      0.0      0.0      0.0   
CDK6                0.0           0.0  ...      0.0      0.0      1.0   
CDKN2A              0.0           1.0  ...      0.0      0.0      0.0   
MDM4                0.0           0.0  ...      0.0      0.0      1.0   

         TP_2060  TP_2061  TP_2064  TP_2069  TP_2077  TP_2078  TP_2079  
level_0                                                                 
AR           1.0      1.0      1.0      1.0      0.0      0.0      1.0  
CDK4         0.0      0.0      0.0      0.0      0.0      1.0      0.0  
CDK6         0.0      0.0      0.0      1.0      0.0      0.0      1.0  
CDKN2A       0.0      1.0      0.0      1.0      0.0      0.0      0.0  
MDM4         0.0      1.0      1.0      0.0      0.0      1.0      0.0  

[5 rows x 1011 columns]

In [15]:
run_mutex(x_df_5, pairs, permutations=2000,saving_file ='mutex_all_cnv_5' )

AR
TP53
0.9645 0.0355
AR
MDM4
1.0 0.0
AR
CDK4
1.0 0.0
AR
CDK6
0.982 0.0235
AR
CDKN2A
0.9885 0.0175
AR
RB1
0.0715 0.9405
TP53
MDM4
0.161 0.869
TP53
CDK4
0.1435 0.928
TP53
CDK6
0.006 0.994
TP53
CDKN2A
1.0 0.0
TP53
RB1
0.0 1.0
MDM4
CDK4
1.0 0.0
MDM4
CDK6
1.0 0.0
MDM4
CDKN2A
0.976 0.0295
MDM4
RB1
0.16 0.8755
CDK4
CDK6
0.4775 0.642
CDK4
CDKN2A
0.7015 0.3935
CDK4
RB1
0.0 1.0
CDK6
CDKN2A
0.845 0.2325
CDK6
RB1
0.0 1.0
CDKN2A
RB1
0.1855 0.862


g1      g2  mutex_pvalue  co_occurence_pvalue    zscore  signal  \
0       AR    TP53        0.9645               0.0355 -1.750681     690   
1       AR    MDM4        1.0000               0.0000 -5.893732     399   
2       AR    CDK4        1.0000               0.0000 -3.998779     338   
3       AR    CDK6        0.9820               0.0235 -1.961861     475   
4       AR  CDKN2A        0.9885               0.0175 -2.269935     337   
5       AR     RB1        0.0715               0.9405  1.484890     772   
6     TP53    MDM4        0.1610               0.8690  1.137128     695   
7     TP53    CDK4        0.1435               0.9280  1.265410     634   
8     TP53    CDK6        0.0060               0.9940  2.475025     771   
9     TP53  CDKN2A        1.0000               0.0000 -3.931258     633   
10    TP53     RB1        0.0000               1.0000  5.394251    1068   
11    MDM4    CDK4        1.0000               0.0000 -4.344746     343   
12    MDM4    CDK6        1.0000               0.0000 -3.438148     480   
13    MDM4  CDKN2A        0.9760               0.0295 -2.210530     342   
14    MDM4     RB1        0.1600               0.8755  1.098343     777   
15    CDK4    CDK6        0.4775               0.6420  0.210228     419   
16    CDK4  CDKN2A        0.7015               0.3935 -0.369974     281   
17    CDK4     RB1        0.0000               1.0000  3.740292     716   
18    CDK6  CDKN2A        0.8450               0.2325 -0.880499     418   
19    CDK6     RB1        0.0000               1.0000  2.838496     853   
20  CDKN2A     RB1        0.1855               0.8620  0.930911     715   

    coverage  signal_coverage_ratio  
0        539               0.781159  
1        305               0.764411  
2        276               0.816568  
3        380               0.800000  
4        284               0.842730  
5        619               0.801813  
6        557               0.801439  
7        539               0.850158  
8        591               0.766537  
9        514               0.812006  
10       723               0.676966  
11       277               0.807580  
12       372               0.775000  
13       287               0.839181  
14       619               0.796654  
15       360               0.859189  
16       248               0.882562  
17       619               0.864525  
18       353               0.844498  
19       644               0.754982  
20       605               0.846154

In [16]:
run_mutex(x_df_3, pairs, permutations=2000,saving_file ='mutex_all_cnv_3' )

AR
TP53
0.0 1.0
AR
MDM4
0.156 0.928
AR
CDK4
0.2795 0.881
AR
CDK6
0.0 1.0
AR
CDKN2A
0.0 1.0
AR
RB1
0.0 1.0
TP53
MDM4
0.0 1.0
TP53
CDK4
0.006 1.0
TP53
CDK6
0.0 1.0
TP53
CDKN2A
0.0 1.0
TP53
RB1
0.042 0.976
MDM4
CDK4
1.0 0.0
MDM4
CDK6
0.5475 0.72
MDM4
CDKN2A
0.47 0.839
MDM4
RB1
0.131 0.9645
CDK4
CDK6
0.774 0.4045
CDK4
CDKN2A
0.2965 1.0
CDK4
RB1
0.0595 0.9885
CDK6
CDKN2A
0.2265 1.0
CDK6
RB1
0.0 1.0
CDKN2A
RB1
0.2315 0.9405


g1      g2  mutex_pvalue  co_occurence_pvalue    zscore  signal  \
0       AR    TP53        0.0000               1.0000  7.000722     375   
1       AR    MDM4        0.1560               0.9280  1.292803     204   
2       AR    CDK4        0.2795               0.8810  0.740502     190   
3       AR    CDK6        0.0000               1.0000  3.232258     198   
4       AR  CDKN2A        0.0000               1.0000  2.583596     183   
5       AR     RB1        0.0000               1.0000  4.204918     223   
6     TP53    MDM4        0.0000               1.0000  4.986098     245   
7     TP53    CDK4        0.0060               1.0000  3.178498     231   
8     TP53    CDK6        0.0000               1.0000  5.082680     239   
9     TP53  CDKN2A        0.0000               1.0000  3.399513     224   
10    TP53     RB1        0.0420               0.9760  1.739183     264   
11    MDM4    CDK4        1.0000               0.0000 -3.281882      60   
12    MDM4    CDK6        0.5475               0.7200  0.351535      68   
13    MDM4  CDKN2A        0.4700               0.8390  0.604290      53   
14    MDM4     RB1        0.1310               0.9645  1.443357      93   
15    CDK4    CDK6        0.7740               0.4045 -0.450578      54   
16    CDK4  CDKN2A        0.2965               1.0000  1.171448      39   
17    CDK4     RB1        0.0595               0.9885  1.639864      79   
18    CDK6  CDKN2A        0.2265               1.0000  1.260089      47   
19    CDK6     RB1        0.0000               1.0000  2.472800      87   
20  CDKN2A     RB1        0.2315               0.9405  1.072148      72   

    coverage  signal_coverage_ratio  
0        315               0.840000  
1        190               0.931373  
2        181               0.952632  
3        191               0.964646  
4        180               0.983607  
5        210               0.941704  
6        237               0.967347  
7        225               0.974026  
8        234               0.979079  
9        221               0.986607  
10       237               0.897727  
11        53               0.883333  
12        65               0.955882  
13        52               0.981132  
14        90               0.967742  
15        51               0.944444  
16        39               1.000000  
17        78               0.987342  
18        47               1.000000  
19        87               1.000000  
20        71               0.986111

In [17]:
run_mutex(x_df_mets_3, pairs, permutations=2000,saving_file ='mutex_mets_cnv_3' )

AR
TP53
0.0 1.0
AR
MDM4
0.0475 0.9825
AR
CDK4
0.488 0.7625
AR
CDK6
0.0655 0.976
AR
CDKN2A
0.0175 0.9945
AR
RB1
0.0 1.0
TP53
MDM4
0.006 0.994
TP53
CDK4
0.095 0.982
TP53
CDK6
0.024 1.0
TP53
CDKN2A
0.006 0.994
TP53
RB1
0.686 0.4515
MDM4
CDK4
1.0 0.012
MDM4
CDK6
0.786 0.548
MDM4
CDKN2A
0.651 0.712
MDM4
RB1
0.3695 0.8385
CDK4
CDK6
0.851 0.5525
CDK4
CDKN2A
0.5615 1.0
CDK4
RB1
0.315 0.917
CDK6
CDKN2A
0.459 1.0
CDK6
RB1
0.054 1.0
CDKN2A
RB1
0.4515 0.899


g1      g2  mutex_pvalue  co_occurence_pvalue    zscore  signal  \
0       AR    TP53        0.0000               1.0000  6.416440     283   
1       AR    MDM4        0.0475               0.9825  1.861460     185   
2       AR    CDK4        0.4880               0.7625  0.237641     172   
3       AR    CDK6        0.0655               0.9760  1.914035     175   
4       AR  CDKN2A        0.0175               0.9945  2.633663     170   
5       AR     RB1        0.0000               1.0000  4.663097     197   
6     TP53    MDM4        0.0060               0.9940  3.088400     148   
7     TP53    CDK4        0.0950               0.9820  1.573393     135   
8     TP53    CDK6        0.0240               1.0000  2.252810     138   
9     TP53  CDKN2A        0.0060               0.9940  2.390519     133   
10    TP53     RB1        0.6860               0.4515 -0.275276     160   
11    MDM4    CDK4        1.0000               0.0120 -3.112409      37   
12    MDM4    CDK6        0.7860               0.5480 -0.234374      40   
13    MDM4  CDKN2A        0.6510               0.7120  0.209752      35   
14    MDM4     RB1        0.3695               0.8385  0.638155      62   
15    CDK4    CDK6        0.8510               0.5525 -0.313667      27   
16    CDK4  CDKN2A        0.5615               1.0000  0.784154      22   
17    CDK4     RB1        0.3150               0.9170  0.923824      49   
18    CDK6  CDKN2A        0.4590               1.0000  0.873585      25   
19    CDK6     RB1        0.0540               1.0000  1.665350      52   
20  CDKN2A     RB1        0.4515               0.8990  0.678189      47   

    coverage  signal_coverage_ratio  
0        225               0.795053  
1        172               0.929730  
2        164               0.953488  
3        168               0.960000  
4        167               0.982353  
5        184               0.934010  
6        141               0.952703  
7        131               0.970370  
8        134               0.971014  
9        131               0.984962  
10       139               0.868750  
11        32               0.864865  
12        38               0.950000  
13        34               0.971429  
14        59               0.951613  
15        26               0.962963  
16        22               1.000000  
17        48               0.979592  
18        25               1.000000  
19        52               1.000000  
20        46               0.978723

In [18]:
run_mutex(x_df_mets_5, pairs, permutations=2000,saving_file ='mutex_mets_cnv_5' )

AR
TP53
0.0595 0.97
AR
MDM4
0.304 0.78
AR
CDK4
0.6535 0.459
AR
CDK6
0.7555 0.3345
AR
CDKN2A
0.3035 0.822
AR
RB1
0.006 1.0
TP53
MDM4
0.0 1.0
TP53
CDK4
0.03 0.976
TP53
CDK6
0.5115 0.6075
TP53
CDKN2A
0.994 0.012
TP53
RB1
0.762 0.345
MDM4
CDK4
1.0 0.0
MDM4
CDK6
0.982 0.03
MDM4
CDKN2A
0.649 0.4755
MDM4
RB1
0.1245 0.9465
CDK4
CDK6
0.8935 0.1485
CDK4
CDKN2A
0.845 0.232
CDK4
RB1
0.006 1.0
CDK6
CDKN2A
0.8335 0.2375
CDK6
RB1
0.4005 0.7185
CDKN2A
RB1
0.8875 0.1725


g1      g2  mutex_pvalue  co_occurence_pvalue    zscore  signal  \
0       AR    TP53        0.0595               0.9700  1.596703     428   
1       AR    MDM4        0.3040               0.7800  0.606091     333   
2       AR    CDK4        0.6535               0.4590 -0.320006     278   
3       AR    CDK6        0.7555               0.3345 -0.569941     328   
4       AR  CDKN2A        0.3035               0.8220  0.646660     271   
5       AR     RB1        0.0060               1.0000  3.101592     441   
6     TP53    MDM4        0.0000               1.0000  3.110388     381   
7     TP53    CDK4        0.0300               0.9760  2.224243     326   
8     TP53    CDK6        0.5115               0.6075  0.078018     376   
9     TP53  CDKN2A        0.9940               0.0120 -2.337151     319   
10    TP53     RB1        0.7620               0.3450 -0.570170     489   
11    MDM4    CDK4        1.0000               0.0000 -2.990367     231   
12    MDM4    CDK6        0.9820               0.0300 -2.013451     281   
13    MDM4  CDKN2A        0.6490               0.4755 -0.242026     224   
14    MDM4     RB1        0.1245               0.9465  1.311811     394   
15    CDK4    CDK6        0.8935               0.1485 -1.058047     226   
16    CDK4  CDKN2A        0.8450               0.2320 -0.916406     169   
17    CDK4     RB1        0.0060               1.0000  2.913080     339   
18    CDK6  CDKN2A        0.8335               0.2375 -0.841282     219   
19    CDK6     RB1        0.4005               0.7185  0.412827     389   
20  CDKN2A     RB1        0.8875               0.1725 -1.161009     332   

    coverage  signal_coverage_ratio  
0        282               0.658879  
1        242               0.726727  
2        219               0.787770  
3        236               0.719512  
4        220               0.811808  
5        292               0.662132  
6        276               0.724409  
7        261               0.800613  
8        265               0.704787  
9        246               0.771160  
10       289               0.591002  
11       176               0.761905  
12       205               0.729537  
13       182               0.812500  
14       278               0.705584  
15       179               0.792035  
16       140               0.828402  
17       273               0.805310  
18       176               0.803653  
19       274               0.704370  
20       260               0.783133

## cBio (fisher exact)

In [20]:
from scipy.stats import chi2_contingency
import scipy.stats as stats
from sklearn import metrics
import numpy as np

def compare_pair(df, g1, g2):
    cm = metrics.confusion_matrix(df[g1], df[g2], labels=[0,1])
    print(cm)
    A= cm[1,1] #both
    B= cm[1,0] # G1 not G2
    C= cm[0,1] # G2 not G1
    D= cm[0,0] #neither
    OR= (A*D)/(B*C)
    log2_OR = np.log2(OR)
    results_dict={}
    results_dict['G1'] = g1
    results_dict['G2'] = g2
    results_dict['both'] = A
    results_dict['G1 not G2'] = B
    results_dict['G2 not G1'] = C
    results_dict['neither'] = D
    results_dict['OR'] = OR
    results_dict['log2_OR'] = log2_OR
    
    chi2, chi2_pvalue, dof, ex = chi2_contingency(cm)
    results_dict['p_value_chi2'] = chi2_pvalue
    oddsratio, p_value= stats.fisher_exact(cm)
    results_dict['p_value_fisher'] = p_value
#     results_dict['oddsratio'] = oddsratio
    return results_dict

def run_cbio(df, pairs, saving_file):
    results_list =[] 
    for p in pairs:
        g1, g2 =p
        print (g1, g2)
        results_dict = compare_pair(df.T, g1, g2) 
        results_list.append(results_dict)
#         print (results_dict)
    results_df = pd.DataFrame(results_list)
    def label_race (row):
        if row['OR'] >=1.  :
            return 'Co-occurrence'
        else:
            return 'Mutual exclusivity'
    
    results_df['Tendency'] =results_df.apply (lambda row: label_race(row), axis=1)

    results_df ['OR'] = results_df['OR'].map('{:,.3f}'.format)
    results_df ['log2_OR'] = results_df['log2_OR'].map('{:,.3f}'.format)
    results_df ['p_value_fisher'] = results_df['p_value_fisher'].map('{:,.3f}'.format)
    results_df ['p_value_chi2'] = results_df['p_value_chi2'].map('{:,.3f}'.format)
    
    cols= ['G1','G2', 'neither' , 'G1 not G2', 'G2 not G1', 'both','OR',  'log2_OR', 'p_value_chi2', 'p_value_fisher','Tendency']
    results_df = results_df.reindex(cols, axis=1)
    results_df.to_csv('{}.csv'.format(saving_file))
    return results_df



In [21]:
ret_df= run_cbio(x_df_mets_5, pairs,saving_file ='cbio_mets_cnv5' )

AR TP53
[[ 51  92]
 [ 44 146]]
AR MDM4
[[91 52]
 [99 91]]
AR CDK4
[[114  29]
 [131  59]]
AR CDK6
[[97 46]
 [98 92]]
AR CDKN2A
[[113  30]
 [139  51]]
AR RB1
[[ 41 102]
 [ 41 149]]
TP53 MDM4
[[ 57  38]
 [133 105]]
TP53 CDK4
[[ 72  23]
 [173  65]]
TP53 CDK6
[[ 68  27]
 [127 111]]
TP53 CDKN2A
[[ 87   8]
 [165  73]]
TP53 RB1
[[ 44  51]
 [ 38 200]]
MDM4 CDK4
[[157  33]
 [ 88  55]]
MDM4 CDK6
[[128  62]
 [ 67  76]]
MDM4 CDKN2A
[[151  39]
 [101  42]]
MDM4 RB1
[[ 55 135]
 [ 27 116]]
CDK4 CDK6
[[154  91]
 [ 41  47]]
CDK4 CDKN2A
[[193  52]
 [ 59  29]]
CDK4 RB1
[[ 60 185]
 [ 22  66]]
CDK6 CDKN2A
[[157  38]
 [ 95  43]]
CDK6 RB1
[[ 59 136]
 [ 23 115]]
CDKN2A RB1
[[ 73 179]
 [  9  72]]


In [22]:
ret_df= run_cbio(x_df_mets_3, pairs,saving_file ='cbio_mets_cnv3' )

AR TP53
[[108  65]
 [102  58]]
AR MDM4
[[161  12]
 [147  13]]
AR CDK4
[[169   4]
 [152   8]]
AR CDK6
[[165   8]
 [153   7]]
AR CDKN2A
[[166   7]
 [157   3]]
AR RB1
[[149  24]
 [147  13]]
TP53 MDM4
[[192  18]
 [116   7]]
TP53 CDK4
[[202   8]
 [119   4]]
TP53 CDK6
[[199  11]
 [119   4]]
TP53 CDKN2A
[[202   8]
 [121   2]]
TP53 RB1
[[194  16]
 [102  21]]
MDM4 CDK4
[[301   7]
 [ 20   5]]
MDM4 CDK6
[[295  13]
 [ 23   2]]
MDM4 CDKN2A
[[299   9]
 [ 24   1]]
MDM4 RB1
[[274  34]
 [ 22   3]]
CDK4 CDK6
[[307  14]
 [ 11   1]]
CDK4 CDKN2A
[[311  10]
 [ 12   0]]
CDK4 RB1
[[285  36]
 [ 11   1]]
CDK6 CDKN2A
[[308  10]
 [ 15   0]]
CDK6 RB1
[[281  37]
 [ 15   0]]
CDKN2A RB1
[[287  36]
 [  9   1]]


/Users/haithamelmarakeby/anaconda2/envs/nlp/lib/python3.7/site-packages/ipykernel_launcher.py:14: RuntimeWarning: divide by zero encountered in log2
  


In [23]:
ret_df= run_cbio(x_df_3, pairs,saving_file ='cbio_all_cnv3' )

AR TP53
[[696 148]
 [107  60]]
AR MDM4
[[821  23]
 [153  14]]
AR CDK4
[[830  14]
 [158   9]]
AR CDK6
[[820  24]
 [160   7]]
AR CDKN2A
[[831  13]
 [164   3]]
AR RB1
[[801  43]
 [154  13]]
TP53 MDM4
[[774  29]
 [200   8]]
TP53 CDK4
[[786  17]
 [202   6]]
TP53 CDK6
[[777  26]
 [203   5]]
TP53 CDKN2A
[[790  13]
 [205   3]]
TP53 RB1
[[774  29]
 [181  27]]
MDM4 CDK4
[[958  16]
 [ 30   7]]
MDM4 CDK6
[[946  28]
 [ 34   3]]
MDM4 CDKN2A
[[959  15]
 [ 36   1]]
MDM4 RB1
[[921  53]
 [ 34   3]]
CDK4 CDK6
[[960  28]
 [ 20   3]]
CDK4 CDKN2A
[[972  16]
 [ 23   0]]
CDK4 RB1
[[933  55]
 [ 22   1]]
CDK6 CDKN2A
[[964  16]
 [ 31   0]]
CDK6 RB1
[[924  56]
 [ 31   0]]
CDKN2A RB1
[[940  55]
 [ 15   1]]


/Users/haithamelmarakeby/anaconda2/envs/nlp/lib/python3.7/site-packages/ipykernel_launcher.py:14: RuntimeWarning: divide by zero encountered in log2
  


In [24]:
ret_df= run_cbio(x_df_5, pairs,saving_file ='cbio_all_cnv5' )

AR TP53
[[472 342]
 [ 46 151]]
AR MDM4
[[706 108]
 [103  94]]
AR CDK4
[[735  79]
 [135  62]]
AR CDK6
[[631 183]
 [102  95]]
AR CDKN2A
[[727  87]
 [144  53]]
AR RB1
[[392 422]
 [ 44 153]]
TP53 MDM4
[[454  64]
 [355 138]]
TP53 CDK4
[[472  46]
 [398  95]]
TP53 CDK6
[[420  98]
 [313 180]]
TP53 CDKN2A
[[497  21]
 [374 119]]
TP53 RB1
[[288 230]
 [148 345]]
MDM4 CDK4
[[734  75]
 [136  66]]
MDM4 CDK6
[[639 170]
 [ 94 108]]
MDM4 CDKN2A
[[724  85]
 [147  55]]
MDM4 RB1
[[392 417]
 [ 44 158]]
CDK4 CDK6
[[651 219]
 [ 82  59]]
CDK4 CDKN2A
[[763 107]
 [108  33]]
CDK4 RB1
[[392 478]
 [ 44  97]]
CDK6 CDKN2A
[[658  75]
 [213  65]]
CDK6 RB1
[[367 366]
 [ 69 209]]
CDKN2A RB1
[[406 465]
 [ 30 110]]


## PAN-cancer mets dataset

In [25]:
external_dir = join(PROSTATE_DATA_PATH, 'external_validation/Met500')
external_dir

'/Users/haithamelmarakeby/PycharmProjects/pnet2/_database/prostate/external_validation/Met500'

In [42]:
mut_df_ext = pd.read_csv(join(external_dir, 'Met500_mut_matrix.csv'), index_col=0)
mut_df_ext.index = mut_df_ext.index.str.split('.', 1).str[0]
mut_df_ext.head()

A1BG  A1CF  A2M  A2ML1  A3GALT2  A4GALT  A4GNT  AAAS  AACS  \
Pipeline_ID                                                               
ES_5001       NaN   NaN  NaN    NaN      NaN     NaN    NaN   NaN   NaN   
ES_5004       NaN   NaN  NaN    NaN      NaN     NaN    NaN   NaN   NaN   
ES_5005       NaN   NaN  NaN    NaN      NaN     NaN    NaN   NaN   NaN   
MO_1001       1.0   NaN  NaN    NaN      NaN     NaN    NaN   NaN   NaN   
MO_1002       NaN   NaN  NaN    NaN      NaN     NaN    NaN   NaN   NaN   

             AADAC  ...  ZWILCH  ZWINT  ZXDA  ZXDB  ZXDC  ZYG11A  ZYG11B  ZYX  \
Pipeline_ID         ...                                                         
ES_5001        NaN  ...     NaN    NaN   NaN   NaN   NaN     NaN     NaN  NaN   
ES_5004        NaN  ...     NaN    NaN   NaN   NaN   NaN     NaN     NaN  NaN   
ES_5005        NaN  ...     NaN    NaN   NaN   NaN   NaN     NaN     NaN  NaN   
MO_1001        NaN  ...     NaN    NaN   NaN   NaN   NaN     NaN     NaN  NaN   
MO_1002        NaN  ...     NaN    NaN   NaN   NaN   NaN     NaN     NaN  NaN   

             ZZEF1  ZZZ3  
Pipeline_ID               
ES_5001        NaN   NaN  
ES_5004        NaN   NaN  
ES_5005        NaN   NaN  
MO_1001        NaN   NaN  
MO_1002        1.0   NaN  

[5 rows x 16576 columns]

In [43]:
mut_df_ext.shape

(500, 16576)

In [44]:
mut_df_ext_selected = mut_df_ext.loc[:, selected_genes].copy()
mut_df_ext_selected.fillna(0, inplace=True)
mut_df_ext_selected.head()

AR  TP53  MDM4  CDK4  CDK6  CDKN2A  RB1
Pipeline_ID                                          
ES_5001      0.0   1.0   0.0   0.0   0.0     0.0  0.0
ES_5004      0.0   1.0   0.0   0.0   0.0     0.0  0.0
ES_5005      0.0   1.0   0.0   0.0   0.0     0.0  0.0
MO_1001      0.0   1.0   0.0   0.0   0.0     0.0  0.0
MO_1002      0.0   0.0   0.0   0.0   0.0     0.0  0.0

In [34]:
cnv_df_ext = pd.read_csv(join(external_dir, 'Met500_cnv.txt'), sep='\t', index_col=0)

ES_5001  ES_5004  ES_5005  MO_1001  MO_1002  MO_1005  MO_1007  \
gene                                                                    
UBE2Q1      1.0      1.0      1.0      1.0      1.0      0.0      0.0   
RNF14       0.0      1.0      0.0      1.0      1.0      0.0      1.0   
UBE2Q2      0.0      0.0      0.0      1.0      1.0      0.0      1.0   
RNF10       0.0      0.0      0.0      1.0      0.0      0.0      0.0   
RNF11       0.0      0.0      1.0      1.0      0.0      0.0      0.0   

        MO_1008  MO_1011  MO_1012  ...  TP_2109  TP_2118  TP_2119  TP_2120  \
gene                               ...                                       
UBE2Q1      0.0      0.0      1.0  ...      1.0      1.0      1.0      1.0   
RNF14       0.0      0.0      1.0  ...      0.0      0.0      1.0      1.0   
UBE2Q2      0.0     -1.0      1.0  ...      0.0      0.0      1.0      0.0   
RNF10       0.0     -1.0      1.0  ...     -1.0      0.0      0.0      0.0   
RNF11       0.0      0.0      1.0  ...      0.0      0.0      0.0      1.0   

        TP_2122  TP_2123  TP_2130  TP_2131  TP_2141  TP_2156  
gene                                                          
UBE2Q1      1.0      0.0      2.0      1.0      0.0      1.0  
RNF14       1.0      0.0      1.0      0.0      0.0      1.0  
UBE2Q2      1.0      1.0      1.0      0.0      0.0      1.0  
RNF10       1.0      0.0      1.0      0.0      1.0      1.0  
RNF11       1.0      0.0      1.0      0.0      0.0      1.0  

[5 rows x 500 columns]

In [61]:
cnv_df_ext_selected = cnv_df_ext.T.loc[:, selected_genes].copy()

cnv_df_ext_selected = cnv_df_ext_selected.replace({-1.0: 0., -2.0:1.0, 1.0: 0., 2.0:1.})
cnv_df_ext_selected.fillna(0.0, inplace=True)
cnv_df_ext_selected.head()

gene      AR  TP53  MDM4  CDK4  CDK6  CDKN2A  RB1
ES_5001  0.0   0.0   0.0   0.0   0.0     0.0  0.0
ES_5004  0.0   0.0   0.0   0.0   0.0     0.0  0.0
ES_5005  0.0   0.0   0.0   0.0   0.0     0.0  0.0
MO_1001  0.0   0.0   0.0   0.0   0.0     0.0  0.0
MO_1002  0.0   0.0   0.0   0.0   1.0     0.0  0.0

In [63]:
cnv_df_ext_selected.MDM4.value_counts()

0.0    465
1.0     35
Name: MDM4, dtype: int64

In [64]:
met500_data = pd.concat([mut_df_ext_selected, cnv_df_ext_selected], keys=['mut', 'cnv'], join='inner', axis=1 )

In [65]:
met500_data.head()

mut                                  cnv                             \
          AR TP53 MDM4 CDK4 CDK6 CDKN2A  RB1   AR TP53 MDM4 CDK4 CDK6 CDKN2A   
ES_5001  0.0  1.0  0.0  0.0  0.0    0.0  0.0  0.0  0.0  0.0  0.0  0.0    0.0   
ES_5004  0.0  1.0  0.0  0.0  0.0    0.0  0.0  0.0  0.0  0.0  0.0  0.0    0.0   
ES_5005  0.0  1.0  0.0  0.0  0.0    0.0  0.0  0.0  0.0  0.0  0.0  0.0    0.0   
MO_1001  0.0  1.0  0.0  0.0  0.0    0.0  0.0  0.0  0.0  0.0  0.0  0.0    0.0   
MO_1002  0.0  0.0  0.0  0.0  0.0    0.0  0.0  0.0  0.0  0.0  0.0  1.0    0.0   

              
         RB1  
ES_5001  0.0  
ES_5004  0.0  
ES_5005  0.0  
MO_1001  0.0  
MO_1002  0.0

In [67]:
met500_data.T.reset_index().head()

level_0 level_1  ES_5001  ES_5004  ES_5005  MO_1001  MO_1002  MO_1005  \
0     mut      AR      0.0      0.0      0.0      0.0      0.0      0.0   
1     mut    TP53      1.0      1.0      1.0      1.0      0.0      0.0   
2     mut    MDM4      0.0      0.0      0.0      0.0      0.0      0.0   
3     mut    CDK4      0.0      0.0      0.0      0.0      0.0      0.0   
4     mut    CDK6      0.0      0.0      0.0      0.0      0.0      0.0   

   MO_1007  MO_1008  ...  TP_2109  TP_2118  TP_2119  TP_2120  TP_2122  \
0      0.0      0.0  ...      0.0      0.0      0.0      0.0      0.0   
1      1.0      0.0  ...      0.0      1.0      0.0      1.0      4.0   
2      0.0      0.0  ...      0.0      0.0      0.0      0.0      0.0   
3      0.0      0.0  ...      0.0      0.0      0.0      0.0      0.0   
4      0.0      0.0  ...      0.0      0.0      0.0      0.0      0.0   

   TP_2123  TP_2130  TP_2131  TP_2141  TP_2156  
0      0.0      0.0      0.0      0.0      0.0  
1      0.0      2.0      0.0      1.0      1.0  
2      0.0      0.0      0.0      0.0      0.0  
3      0.0      0.0      0.0      0.0      0.0  
4      0.0      0.0      0.0      0.0      0.0  

[5 rows x 502 columns]

In [68]:
met500_df_3 = met500_data.T.reset_index().groupby('level_1').sum() # all events (OR)
met500_df_3[met500_df_3>0] = 1 # binarize 
met500_df_3.shape

(7, 500)

In [69]:
met500_df_3

ES_5001  ES_5004  ES_5005  MO_1001  MO_1002  MO_1005  MO_1007  \
level_1                                                                  
AR           0.0      0.0      0.0      0.0      0.0      0.0      0.0   
CDK4         0.0      0.0      0.0      0.0      0.0      0.0      0.0   
CDK6         0.0      0.0      0.0      0.0      1.0      0.0      1.0   
CDKN2A       0.0      0.0      0.0      0.0      0.0      0.0      0.0   
MDM4         0.0      0.0      0.0      0.0      0.0      0.0      0.0   
RB1          0.0      0.0      0.0      0.0      0.0      0.0      0.0   
TP53         1.0      1.0      1.0      1.0      0.0      0.0      1.0   

         MO_1008  MO_1011  MO_1012  ...  TP_2109  TP_2118  TP_2119  TP_2120  \
level_1                             ...                                       
AR           0.0      0.0      0.0  ...      0.0      0.0      0.0      0.0   
CDK4         0.0      0.0      0.0  ...      0.0      0.0      0.0      0.0   
CDK6         0.0      0.0      0.0  ...      0.0      0.0      0.0      0.0   
CDKN2A       0.0      0.0      1.0  ...      0.0      1.0      1.0      1.0   
MDM4         0.0      0.0      0.0  ...      0.0      0.0      0.0      0.0   
RB1          0.0      0.0      1.0  ...      0.0      0.0      0.0      0.0   
TP53         0.0      0.0      0.0  ...      0.0      1.0      0.0      1.0   

         TP_2122  TP_2123  TP_2130  TP_2131  TP_2141  TP_2156  
level_1                                                        
AR           0.0      0.0      0.0      0.0      0.0      0.0  
CDK4         0.0      0.0      0.0      0.0      0.0      0.0  
CDK6         0.0      0.0      0.0      0.0      0.0      0.0  
CDKN2A       1.0      0.0      0.0      1.0      0.0      0.0  
MDM4         0.0      0.0      1.0      0.0      0.0      0.0  
RB1          0.0      0.0      0.0      0.0      1.0      1.0  
TP53         1.0      0.0      1.0      0.0      1.0      1.0  

[7 rows x 500 columns]

In [70]:
ret_df= run_cbio(met500_df_3, pairs,saving_file ='met500_cbio_mets_cnv3' )

AR TP53
[[225 223]
 [ 25  27]]
AR MDM4
[[416  32]
 [ 46   6]]
AR CDK4
[[438  10]
 [ 51   1]]
AR CDK6
[[431  17]
 [ 46   6]]
AR CDKN2A
[[371  77]
 [ 44   8]]
AR RB1
[[412  36]
 [ 47   5]]
TP53 MDM4
[[235  15]
 [227  23]]
TP53 CDK4
[[246   4]
 [243   7]]
TP53 CDK6
[[244   6]
 [233  17]]
TP53 CDKN2A
[[216  34]
 [199  51]]
TP53 RB1
[[245   5]
 [214  36]]
MDM4 CDK4
[[453   9]
 [ 36   2]]
MDM4 CDK6
[[447  15]
 [ 30   8]]
MDM4 CDKN2A
[[382  80]
 [ 33   5]]
MDM4 RB1
[[425  37]
 [ 34   4]]
CDK4 CDK6
[[468  21]
 [  9   2]]
CDK4 CDKN2A
[[407  82]
 [  8   3]]
CDK4 RB1
[[452  37]
 [  7   4]]
CDK6 CDKN2A
[[399  78]
 [ 16   7]]
CDK6 RB1
[[439  38]
 [ 20   3]]
CDKN2A RB1
[[376  39]
 [ 83   2]]


In [71]:
run_mutex(met500_df_3, pairs, permutations=2000,saving_file ='met500_mutex_mets_cnv_3' )

AR
TP53
0.0 1.0
AR
MDM4
0.3555 0.804
AR
CDK4
0.326 0.9345
AR
CDK6
0.8445 0.321
AR
CDKN2A
0.0 1.0
AR
RB1
0.1435 0.9465
TP53
MDM4
0.0 1.0
TP53
CDK4
0.138 0.952
TP53
CDK6
0.233 0.88
TP53
CDKN2A
0.0 1.0
TP53
RB1
0.911 0.191
MDM4
CDK4
0.8045 0.54
MDM4
CDK6
1.0 0.0
MDM4
CDKN2A
0.0055 1.0
MDM4
RB1
0.2145 0.892
CDK4
CDK6
0.9475 0.225
CDK4
CDKN2A
0.53 0.709
CDK4
RB1
0.9705 0.0765
CDK6
CDKN2A
0.5695 0.596
CDK6
RB1
0.5485 0.732
CDKN2A
RB1
0.0 1.0


g1      g2  mutex_pvalue  co_occurence_pvalue    zscore  signal  \
0       AR    TP53        0.0000               1.0000  5.350893     302   
1       AR    MDM4        0.3555               0.8040  0.644699      90   
2       AR    CDK4        0.3260               0.9345  0.910256      63   
3       AR    CDK6        0.8445               0.3210 -0.804866      75   
4       AR  CDKN2A        0.0000               1.0000  2.558734     137   
5       AR     RB1        0.1435               0.9465  1.387068      93   
6     TP53    MDM4        0.0000               1.0000  3.662521     288   
7     TP53    CDK4        0.1380               0.9520  1.473565     261   
8     TP53    CDK6        0.2330               0.8800  0.915694     273   
9     TP53  CDKN2A        0.0000               1.0000  5.821476     335   
10    TP53     RB1        0.9110               0.1910 -1.052642     291   
11    MDM4    CDK4        0.8045               0.5400 -0.293381      49   
12    MDM4    CDK6        1.0000               0.0000 -3.108888      61   
13    MDM4  CDKN2A        0.0055               1.0000  2.565239     123   
14    MDM4     RB1        0.2145               0.8920  0.973441      79   
15    CDK4    CDK6        0.9475               0.2250 -1.197231      34   
16    CDK4  CDKN2A        0.5300               0.7090  0.247589      96   
17    CDK4     RB1        0.9705               0.0765 -1.845221      52   
18    CDK6  CDKN2A        0.5695               0.5960  0.101310     108   
19    CDK6     RB1        0.5485               0.7320  0.298216      64   
20  CDKN2A     RB1        0.0000               1.0000  3.729270     126   

    coverage  signal_coverage_ratio  
0        275               0.910596  
1         84               0.933333  
2         62               0.984127  
3         69               0.920000  
4        129               0.941606  
5         88               0.946237  
6        265               0.920139  
7        254               0.973180  
8        256               0.937729  
9        284               0.847761  
10       255               0.876289  
11        47               0.959184  
12        53               0.868852  
13       118               0.959350  
14        75               0.949367  
15        32               0.941176  
16        93               0.968750  
17        48               0.923077  
18       101               0.935185  
19        61               0.953125  
20       124               0.984127

In [72]:
met500_df_3.head()

ES_5001  ES_5004  ES_5005  MO_1001  MO_1002  MO_1005  MO_1007  \
level_1                                                                  
AR           0.0      0.0      0.0      0.0      0.0      0.0      0.0   
CDK4         0.0      0.0      0.0      0.0      0.0      0.0      0.0   
CDK6         0.0      0.0      0.0      0.0      1.0      0.0      1.0   
CDKN2A       0.0      0.0      0.0      0.0      0.0      0.0      0.0   
MDM4         0.0      0.0      0.0      0.0      0.0      0.0      0.0   

         MO_1008  MO_1011  MO_1012  ...  TP_2109  TP_2118  TP_2119  TP_2120  \
level_1                             ...                                       
AR           0.0      0.0      0.0  ...      0.0      0.0      0.0      0.0   
CDK4         0.0      0.0      0.0  ...      0.0      0.0      0.0      0.0   
CDK6         0.0      0.0      0.0  ...      0.0      0.0      0.0      0.0   
CDKN2A       0.0      0.0      1.0  ...      0.0      1.0      1.0      1.0   
MDM4         0.0      0.0      0.0  ...      0.0      0.0      0.0      0.0   

         TP_2122  TP_2123  TP_2130  TP_2131  TP_2141  TP_2156  
level_1                                                        
AR           0.0      0.0      0.0      0.0      0.0      0.0  
CDK4         0.0      0.0      0.0      0.0      0.0      0.0  
CDK6         0.0      0.0      0.0      0.0      0.0      0.0  
CDKN2A       1.0      0.0      0.0      1.0      0.0      0.0  
MDM4         0.0      0.0      1.0      0.0      0.0      0.0  

[5 rows x 500 columns]